[toolchain]
anchor_version = "0.32.1"
solana_version = "2.2.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
meridian_jpy = "JPYm1111111111111111111111111111111111111111"
transfer_hook = "THKm1111111111111111111111111111111111111111"
securities_engine = "SECm1111111111111111111111111111111111111111"
rwa_registry = "RWAm1111111111111111111111111111111111111111"
oracle = "ORCm1111111111111111111111111111111111111111"
compliant_registry = "CRGm1111111111111111111111111111111111111111"

[programs.devnet]
meridian_jpy = "JPYm1111111111111111111111111111111111111111"
transfer_hook = "THKm1111111111111111111111111111111111111111"
securities_engine = "SECm1111111111111111111111111111111111111111"
rwa_registry = "RWAm1111111111111111111111111111111111111111"
oracle = "ORCm1111111111111111111111111111111111111111"
compliant_registry = "CRGm1111111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
