[toolchain]
anchor_version = "0.32.1"
solana_version = "2.2.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
meridian_jpy = "HdaUf9PL9ncd1AgXbA13P9ss6mLtCVdGZfroZB4q6CwP"
transfer_hook = "4CoN4C1mqdkgvgQeXMSa1Pnb7guFH89DekEvRHgKmivf"
securities_engine = "7eoNfGXF5kdonbCwAs1tvaPc5HZFnVC2pgiFDnuG3yTe"
rwa_registry = "BMej5CMvLs8xN3TGj7o9HKV2px6gyycS26y5ZJSBjL5D"
oracle = "BXm2LiGwT2AR267gqd1yNbckytysBD8LCaov5zTGUDpw"
compliant_registry = "hhcx645NBLLRrKry3dkDMTMzZfrCUEJk3UurUYBxjww"

[programs.devnet]
meridian_jpy = "HdaUf9PL9ncd1AgXbA13P9ss6mLtCVdGZfroZB4q6CwP"
transfer_hook = "4CoN4C1mqdkgvgQeXMSa1Pnb7guFH89DekEvRHgKmivf"
securities_engine = "7eoNfGXF5kdonbCwAs1tvaPc5HZFnVC2pgiFDnuG3yTe"
rwa_registry = "BMej5CMvLs8xN3TGj7o9HKV2px6gyycS26y5ZJSBjL5D"
oracle = "BXm2LiGwT2AR267gqd1yNbckytysBD8LCaov5zTGUDpw"
compliant_registry = "hhcx645NBLLRrKry3dkDMTMzZfrCUEJk3UurUYBxjww"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "NODE_OPTIONS='--no-experimental-strip-types' yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
